version: "3.9"
services:

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - uwsgi_data:/tmp/uwsgi/
      - static_asset:/var/www/mysite/static/
    ports:
      - "8888:80"
    depends_on: 
      - django

  django:
    build: ./web
    restart: always
    command: uwsgi --ini /code/mysite.uwsgi.ini
    volumes:
      - uwsgi_data:/tmp/uwsgi/
      - static_asset:/code/static/

volumes:
  uwsgi_data:
  static_asset:
